apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "jenkins-config.name" . }}
    labels:
        group: {{ .Values.group }}
data:
    JENKINS_HOST: {{ .Values.jenkins.host }}
    JENKINS_URL: {{ printf "http://%s" .Values.jenkins.host }}
