apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  labels:
    "app.kubernetes.io/name": 'sonarqube'
    "app.kubernetes.io/instance": "sonarqube"
    group: {{ .Values.group }}
data:
  SONARQUBE_URL: {{ .Values.url | quote }}
