apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-access
  labels:
    "app.kubernetes.io/name": 'sonarqube'
    "app.kubernetes.io/instance": "sonarqube"
    group: {{ .Values.group }}
type: Opaque
stringData:
  SONARQUBE_PASSWORD: {{ .Values.username }}
  SONARQUBE_USER: {{ .Values.password }}
